Traceback (most recent call last):
  File "distr_plan.py", line 521, in <module>
    main()
  File "distr_plan.py", line 29, in main
    optimize_script(args.input_ir, args.compile_optimize_only)
  File "distr_plan.py", line 68, in optimize_script
    execute(eager_distributed_graph.serialize_as_JSON(), config.config['output_dir'],
  File "/home/nikos/dish/compiler/impl.py", line 17, in execute
    exec_obj = subprocess.run(output_script, shell=True, executable="/bin/bash")
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/bash'
Traceback (most recent call last):
  File "/home/nikos/dish/compiler/dish.py", line 96, in <module>
    main()
  File "/home/nikos/dish/compiler/dish.py", line 37, in main
    execute_script(args.output, args.output_optimized, args.compile_optimize_only)
  File "/home/nikos/dish/compiler/dish.py", line 93, in execute_script
    exec_obj.check_returncode()
  File "/usr/local/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/bin/bash', '../evaluation//intermediary/micro_1000_4_distr.sh']' returned non-zero exit status 1.

real	379m33.545s
user	378m30.424s
sys	0m53.688s
